map_name: Town06
delta_seconds: 0.1
preset_ego_route: [150, 250]  # TODO: 请替换为实际的交叉口路点
rebuild_roadgraph: False
updateInterval: 10
deArea: 50
max_veh_num: 40
carlaImage: True
vehicleSpawnInterval: 50
vehicleVisibleRange: 100
vehicleCheckRange: 50
max_steps: 1000  # 最大时间步限制
init:
  veh_num: 15  # TODO: 根据交叉口场景需求调整车辆数量
  travel_distance: 2000  # TODO: 根据交叉口场景需求调整行驶距离 