map_name: Town06
delta_seconds: 0.1
ego_path: None
rebuild_roadgraph: False
updateInterval: 10
deArea: 50
max_veh_num: 20
carlaImage: True
vehicleSpawnInterval: 50
vehicleVisibleRange: 100
vehicleCheckRange: 50
init:
  veh_num: 10
  travel_distance: 1000
