map_name: Town06
ego_path: None
rebuild_roadgraph: False
updateInterval: 10
deArea: 50
max_veh_num: 20
carlaImage: False
vehicleSpawnInterval: 50
vehicleVisibleRange: 100
vehicleCheckRange: 50
init:
  veh_num: 10
  travel_distance: 2000
