OPENAI_API_TYPE: 'openai'
REAL_OPENAI_KEY: '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' #'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'
CHATGPT_MODEL: GPT-16
EMBEDDING_MODEL: ada-002
OPENAI_API_BASE: https://east-us-api.openai.azure.com/
OPENAI_API_VERSION: "2023-07-01-preview"
OPENAI_API_KEY: '343b4715940c431b9e6193d679c15c71'
GPT4_MODEL: GPT-4
GPT4_API_BASE: https://japan-api.openai.azure.com/
GPT4_API_VERSION: "2023-07-01-preview"
GPT4_API_KEY: 'd347b4d42b0d4ebf93ccf13d4b7da88f'