OPENAI_API_TYPE: 'azure'
REAL_OPENAI_KEY: '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' #'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'
CHATGPT_MODEL: GPT-16
EMBEDDING_MODEL: ada-002
OPENAI_API_BASE: https://east-us-api.openai.azure.com/
OPENAI_API_VERSION: "2023-03-15-preview"
OPENAI_API_KEY: '75ecfb81695d4030b161267a3a8c9b46'
GPT4_MODEL: GPT-4
GPT4_API_BASE: https://japan-api.openai.azure.com/
GPT4_API_VERSION: "2023-07-01-preview"
GPT4_API_KEY: 'd347b4d42b0d4ebf93ccf13d4b7da88f'

# Optional for LangSmith
LANGCHAIN_TRACING_V2: true
LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
LANGCHAIN_API_KEY: ls__8a9ec82010f1488e934aefab1d5eea03
LANGCHAIN_PROJECT: DiLu